### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by fromleaf** [fromleaf/fromleaf.mypage#1]
- [ ] 페이지 시작할 때, DB Data가져오는 것 때문인지 많이 느리다. Optimization 해야겠다. -> 원래 느린건지, 수정했는데도 그렇게 빠르지 않다. 성능 테스트 해봐야겠다. LoadRunner라는걸 써보거나, Azure에서 제공하는걸 함 써봐야지.
- [ ] Skill Page - Level 이미지 표시(***oo)
- [ ] Studying Page - Django 공부하면서 만들었던 것들 볼 수 있도록 올려놔야겠다.
- [ ] Data insert하는 방법 JSON현태로 바꿔볼까? (inser_user_data.py에 구현하면 될 것 같다.)
- [ ] insert할 때, 각 attribute 입력할 때, **kwargs로 변경해야겠다. 진작에 이걸로 했었어야 했는데..
- [ ] 사용자 정보를 Django에서 제공해주는 기본 기능으로 바꿀 수 있을 것 같은데....
- [ ] Member 생성 시에 자동으로 Page 관련된 부분들 생성하도록 해야할 것 같다.
- [ ] 예외처리 부분이 많이 빠져있다. 그리고 로그 남기는 기능도 추가 해야겠다.
- [ ] Unit Test Code도 작성해보자.
- [ ] Interesting 페이지도 하나 만들까?
- [ ] MySkillView 클래스에서 각 스킬별 리스트에 저장하는 로직이 너무 별로다...뭔가 좋은 방법이 있을 것 같은데
- [ ] REST API(http://www.django-rest-framework.org/)써서 함 구현해봐야지

**Comment by fromleaf** [comment]
- Azure 서버가 무료 서버라서 그런지 모바일에서 페이지 띄우면 여전히 느리다...
- 나머지 두 개는 했음
